dataset_path: longvideobench/LongVideoBench
dataset_kwargs:
  token: True
  cache_dir: /usr/project/xtmp/jc923/cache_center/huggingface/datasets/LongVideoBench
  video: True
  force_download: False
  local_files_only: False
  # From_YouTube: True
task: longvideobench_val_v
test_split: validation
doc_to_visual: !function utils.longvideobench_doc_to_visual_v
doc_to_text: !function utils.longvideobench_doc_to_text
doc_to_target: "correct_choice"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
process_results: !function utils.longvideobench_process_results
metric_list:
  # Overall metric
  - metric: lvb_acc
    aggregation: !function utils.longvideobench_aggregate_results
    higher_is_better: true
  # Duration group dimension metrics
  - metric: lvb_duration_group
    aggregation: !function utils.longvideobench_aggregate_duration_group
    higher_is_better: true
  # Question category dimension metrics
  - metric: lvb_question_category
    aggregation: !function utils.longvideobench_aggregate_question_category
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with the option's letter from the given choices directly.\n"
  